import os
import requests

def gen_condition(width):
    key,value = width[:2]
    if ".." in key:
        start,end=key.split("..")[:2]
        return f"""\tif (0x{start} <= c && c <= 0x{end}){{return "{value}"}}"""
    return f"""\tif (c==0x{key}){{return "{value}"}}"""

url = "https://www.unicode.org/Public/15.0.0/ucd/EastAsianWidth-15.0.0d5.txt"

res = requests.get(url)

width_map = [x.split("#")[0].strip().split(";") 
             for x in res.text.split("\n") 
             if x.split("#")[0] != ""]

condition = "\n".join([gen_condition(x) for x in width_map])

go_file = f"""package unicode

/*
auto genarated by file from https://www.unicode.org/Public/15.0.0/ucd/EastAsianWidth-15.0.0d5.txt
do not edit this file unless you know what you are doing.
*/

func GetEastAsianWidth(c rune) int {{
	code := east_asian_width(c)
	switch code {{
	case "F", "W":
		return 2
	default:
		return 1
	}}
}}

func east_asian_width(c rune) string {{
{condition}
    return "N"
}}
"""

file = "east_asian_width.go"
os.makedirs(os.path.dirname(os.path.abspath(file)), exist_ok=True)
with open(file,"w") as f:
    f.write(go_file)